Livraison 2 : Tâche Guiconf , afficher la liste des conférences et ses champs pour édition
13tomoore/J-Confs pull request #10
Opened 2019-06-03 18:39 UTC by nikolaspaci

Cette PR est dans la continuité de la PR #3 qui pour rappelle avait pour but (entres autres) de mettre en place les méthodes permettant de lire l'ensemble des conférences d'un fichier icalendar ( et non seulement une comme autrefois). 
Ainsi cette PR s'oriente plus sur l'interface graphique et les pré-conditions de saisie:
-Utilisation de Gridlayout pour disposition des widgets.
-Synchronisation entre la widget liste de SWT et les champs ( lors du clique sur une conférence présente dans la liste, affichage des différentes informations de cette conférence dans différents widgets adaptés (texte et datetime)
-Vérification du respect du bon format de saisie pour chaque édition de conférence et envoie d'un message en cas de mauvais format.
La méthode permettant de rendre effective la modification d'une conférence (delete + create) au sein d'un fichier iCalendar est réalisée par l'autre team de développement.

2019-06-04 10:33 UTC, oliviercailloux requested changes
ECL FORMAT (je continue la review après correction).

2019-06-04 10:33 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/jconfs/GuiListConferences.java
> +	private ArrayList<Conference> listConferencesUser;
Dépendre de `List` et non `ArrayList`, car plus générale.

2019-06-04 16:38 UTC, nikolaspaci commented on src/main/java/io/github/oliviercailloux/y2018/jconfs/GuiListConferences.java
> +	private ArrayList<Conference> listConferencesUser;
Généralisation effectuée.

2019-06-04 16:44 UTC, nikolaspaci commented
Import du fichier de préférence  éclipse du professeur ==> plus aucun warning sur la classe modifiée.
Vérification si Format respectée ==>cela semble être le cas maintenant.

2019-06-05 17:21 UTC, oliviercailloux requested changes
Classe et méthodes trop longues, code difficile à lire et comprendre rapidement. Raccourcir avec method references et autres découpes en sous-méthodes où approprié.

2019-06-05 17:21 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/jconfs/GuiListConferences.java
> + * @author nikola Gui
Formatage incomplet

2019-06-05 17:21 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/jconfs/GuiListConferences.java
> +	private java.util.List<Conference> listConferencesUser;
Inverser SVP : utiliser List tout court pour java.util.List (par habitude et convention, la classe List étant beaucoup plus habituelle dans un code général) et nom complet pour la liste au sens SWT.

2019-06-05 17:21 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/jconfs/GuiListConferences.java
> +	 * List that stocks all of conferences from ConferenceReader
Commentaire inapproprié. Votre code doit fonctionner tout aussi bien si la liste de conférence ne vient pas de ConferenceReader mais d’ailleurs.

2019-06-05 17:21 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/jconfs/GuiListConferences.java
> +	 * @throws InvalidConferenceFormatException
Enlever toutes ces mentions @throws inutiles. Le reste du commentaire ne me semble pas à sa place (ni très utile) d’ailleurs. Si vous voulez commenter l’objectif de cette classe en général, le commentaire doit être placé sur la classe.

2019-06-05 17:21 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/jconfs/GuiListConferences.java
> +		};
Utiliser une method reference vers une méthode de la classe créée à cet effet.

2019-06-05 17:21 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/jconfs/GuiListConferences.java
> +		listConferences.addSelectionListener(new SelectionListener() {
Lire la javadoc et utiliser une method reference.

2019-06-05 17:21 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/jconfs/GuiListConferences.java
> +						getConferences();
Ce code ne me semble pas sauver grand-chose.

2019-06-05 17:30 UTC, nikolaspaci commented on src/main/java/io/github/oliviercailloux/y2018/jconfs/GuiListConferences.java
> +						getConferences();
En effet les méthodes permettant de supprimer et sauver la conférence sont réalisées par la team 2 sur la PR #12 . Lors des essais sur la branche "dev" celles-ci fonctionnaient. Cependant, il s'agit de deux tâches différente donc deux PR différentes, ces deux méthodes ne sont donc pas encore présente au sein de cette branche.

2019-06-08 09:59 UTC, oliviercailloux requested changes
Prendre tous mes commentaires précédents en compte.

Concernant la sauvegarde, loggez simplement (niveau warn) que la sauvegarde n’est pas encore implémentée là où vous êtes censé sauvegarder, pour que le lecteur du code s’y retrouve.

2019-06-08 09:59 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/jconfs/GuiListConferences.java
> -	}*/
BP style comments

2019-06-08 10:13 UTC, nikolaspaci commented
En effet merci , ajout des méthode references et du logger de niveau warm réalisé. Et suppression du code commenté.

2019-06-12 20:29 UTC, nikolaspaci commented
Il m'est difficile de raccourcir le code étant donné que la plupart du code est destiné à l'interface graphique (instanciation des widgets,disposition des widgets...).

2019-06-13 17:19 UTC, oliviercailloux requested changes
Il peut être difficile de raccourcir la classe, mais il n’est pas très difficile de raccourcir certaines méthodes en les découpant en sous-méthodes.
Prendre tous mes commentaires précédents en compte (ou y répondre).

2019-06-13 17:42 UTC, nikolaspaci commented on src/main/java/io/github/oliviercailloux/y2018/jconfs/GuiListConferences.java
> +		};
Utilisation de la method refernce done

2019-06-13 18:35 UTC, nikolaspaci commented on src/main/java/io/github/oliviercailloux/y2018/jconfs/GuiListConferences.java
> + * @author nikola Gui
correction effectuée

2019-06-13 18:35 UTC, nikolaspaci commented on src/main/java/io/github/oliviercailloux/y2018/jconfs/GuiListConferences.java
> +	private java.util.List<Conference> listConferencesUser;
Modification effectuée

2019-06-13 18:35 UTC, nikolaspaci commented on src/main/java/io/github/oliviercailloux/y2018/jconfs/GuiListConferences.java
> +	 * List that stocks all of conferences from ConferenceReader
Commentaire modifié

2019-06-13 18:36 UTC, nikolaspaci commented on src/main/java/io/github/oliviercailloux/y2018/jconfs/GuiListConferences.java
> +	 * @throws InvalidConferenceFormatException
Commentaire supprimé

2019-06-13 18:38 UTC, nikolaspaci commented on src/main/java/io/github/oliviercailloux/y2018/jconfs/GuiListConferences.java
> +		listConferences.addSelectionListener(new SelectionListener() {
Method réference utilisé et javadoc lue ( "castage" du widget en text pour pouvoir utilisé la méthode getText)

2019-06-13 18:43 UTC, nikolaspaci commented on src/main/java/io/github/oliviercailloux/y2018/jconfs/GuiListConferences.java
> -	}*/
Respect de : "No code disabled using comments "

2019-06-13 18:51 UTC, oliviercailloux requested changes

2019-06-13 18:51 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/jconfs/GuiListConferences.java
> +		listConferences.addSelectionListener(new SelectionListener() {
Je ne vois pas de method reference utilisée à cet endroit sur la diff affichée sur GitHub.

2019-06-13 19:06 UTC, nikolaspaci commented
La review est elle sur le listener de txtRegisFee ou bien celui de listConferences ? Car la méthode référence réalisée porte sur txtRegisFee, celle de listConferences n'a pas été réalisé".

2019-06-13 19:10 UTC, oliviercailloux commented
Sur `listConferences`.

2019-06-17 14:46 UTC, nikolaspaci commented
Ajout de method réference demandée et création d'une méthode qui crée les widgets ainsi que une autre méthode pour les Listenner ( rend le clair plus lisible)

2019-06-17 15:56 UTC, oliviercailloux requested changes
FORMAT

2019-06-17 15:56 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/jconfs/ListennerAction.java
> +public class ListennerAction {
Listener, pas Listenner

2019-06-17 15:56 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/jconfs/ListennerAction.java
> +	public static void CheckTextInput(VerifyEvent e) {
Respecter les conventions de nommage svp

2019-06-17 15:56 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/jconfs/GuiListConferences.java
> +	public void CreateWidgets() throws IOException, ParserException, InvalidConferenceFormatException {
BP style writing code

2019-06-17 16:18 UTC, nikolaspaci commented on src/main/java/io/github/oliviercailloux/y2018/jconfs/GuiListConferences.java
> +	public void CreateWidgets() throws IOException, ParserException, InvalidConferenceFormatException {
Ajout description et convention nom

2019-06-17 16:18 UTC, nikolaspaci commented on src/main/java/io/github/oliviercailloux/y2018/jconfs/ListennerAction.java
> +	public static void CheckTextInput(VerifyEvent e) {
changement effectué

2019-06-17 16:19 UTC, nikolaspaci commented on src/main/java/io/github/oliviercailloux/y2018/jconfs/ListennerAction.java
> +public class ListennerAction {
erreur modifiée

2019-06-17 17:05 UTC, oliviercailloux approved these changes

2019-06-17 18:28 UTC, merged