Refactoring
13tomoore/J-Confs pull request #11
Opened 2019-06-03 20:01 UTC by aliliKM

Livraison 2 - Modification des constructeurs / Classe Conference immuable

2019-06-04 17:55 UTC, oliviercailloux commented
INSTR SVP

2019-06-05 08:22 UTC, aliliKM commented
Conflits réglés

2019-06-08 09:34 UTC, oliviercailloux requested changes
FOCUS
Commencez par formater systématiquement le code (tâche en soi).
BP Resources
DER
Le fichier LICENCE doit rester à la racine, par convention.

2019-06-13 20:53 UTC, aliliKM commented
Les tâches ont été réparties sur deux nouvelles branches. Est-il possible de supprimer celle-ci ?

2019-06-16 22:28 UTC, oliviercailloux commented
Supprimer, non, car je désire conserver l’historique. Fermez ce PR et ouvrez-en d’autres si c’est ce que vous souhaitez.

2019-06-17 13:43 UTC, closed without merging