Conference writer task
13tomoore/J-Confs pull request #12
Opened 2019-06-03 20:33 UTC by 13tomoore

**Work performed (for livraison number 2) :**

-Correction of the method Equals in class Conference. Comparaison of attribute registrationFee (of type Double) was badly implement
-New method called deleteConference which allows you to delete a conference from ics File
-New method called saveIcsFile
-New method called fileExists which will be used to determines whether the conference will be added to a new ics file or an existing one
-Rename of a method to addConference. It now create a XComponent rather than a EVENT object. Moreover you can now add a Conference to an existing ics file
-The format of the dates when writing into ics file is now correct
-JUNIT class test

2019-06-04 17:50 UTC, oliviercailloux requested changes
FORMAT
Je continue la review après correction.

2019-06-04 17:50 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/jconfs/ConferenceWriter.java
> +				System.out.println("indeed");
What’s that?

2019-06-04 17:50 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/jconfs/ConferenceWriter.java
> +			e.printStackTrace();
EXC

2019-06-05 18:13 UTC, oliviercailloux requested changes
FORMAT (cf. Tools.adoc, aide d’Eclipse)

2019-06-05 18:30 UTC, oliviercailloux requested changes
FORMAT (cf. Tools.adoc, aide d’Eclipse)

2019-06-05 18:30 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/jconfs/Conference.java
> +					&& Double.compare(registrationFee, conference2.registrationFee)==0 && city.equals(conference2.city)
Objects.equal conviendrait mieux ici.

2019-06-05 18:30 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/jconfs/ConferenceWriter.java
> +	 * @return
doc format incorrect, voyez le résultat par vous-même

2019-06-05 18:30 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/jconfs/ConferenceWriter.java
> +	public static boolean icsFileExists(String calFile) {
Je ne suis pas convaincu de l’utilité de cette méthode. Vous êtes censé savoir ce qu’il y a dans votre class path au moment d’écrire votre code ! Cela ne doit pas être dynamique.

2019-06-05 18:30 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/jconfs/ConferenceWriter.java
> +	 * @throws InvalidConferenceFormatException
BP Style javadoc

2019-06-05 18:30 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/jconfs/ConferenceWriter.java
> +		reader.close();
Pas besoin du close puisque try-with-resources

2019-06-05 18:30 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/jconfs/ConferenceWriter.java
> +		}
Cette logique n’est pas très élégante et peut surprendre votre utilisateur. Le code ne devrait pas changer de comportement alors qu’on appelle la même méthode selon que le nom du fichier donné existe dans le class path (on peut ne pas y avoir pensé). Et comment faire si on veut lire un fichier hors du class path mais qui par hasard a le nom d’un fichier dans le class path ? En outre, il n’est pas très élégant de relire tout le fichier, alors qu’on vient probablement de le lire (sinon, comment obtenir la conférence qu’on veut effacer ?).

Par ailleurs, je ne comprends pas ce que le code est censé faire quand le fichier n’est pas dans le class path. Qu’y a-t-il à enlever dans ce cas ?

2019-06-05 18:30 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/jconfs/ConferenceWriter.java
> +		}
Ne jamais écrire dans votre class path.

2019-06-05 18:30 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/jconfs/GuiConference.java
>  					e1.printStackTrace();
EXC

2019-06-05 18:30 UTC, oliviercailloux commented on src/test/java/io/github/oliviercailloux/y2018/TestConferenceWriter.java
> +
Il faut tester que le résultat est conforme à l’attente en comparant avec un fichier dans votre class path.

2019-06-17 14:14 UTC, 13tomoore commented on src/test/java/io/github/oliviercailloux/y2018/TestConferenceWriter.java
> +
Je ferme la PR suite à la discussion que nous avons eu.

2019-06-17 14:36 UTC, closed without merging