adding class diagram for delivery2
13tomoore/J-Confs pull request #15
Opened 2019-06-03 22:00 UTC by jacquesmoati

only readable on eclipse

2019-06-05 16:46 UTC, oliviercailloux commented
Déplacer dans doc. Exporter en PNG pour que je puisse le voir sans installer ObjectAid UML Explorer. Ce dernier semble payant : on peut avoir une « evaluation licence » mais je ne pense pas que ça donne le droit de l’utiliser pour longtemps. Indiquez-moi si je me trompe, sinon il faut à l’avenir utiliser un autre outil. (Trouver un outil gratuit, ou envisager IBM Rational, cf. cours DevOps).

2019-06-06 10:12 UTC, jacquesmoati commented
@oliviercailloux 
Effectivement, il faut installer ObjectAid UML Explorer sur Eclipse. Je pense que l'on peut l'utiliser de manière gratuite à condition de ne pas l'upgrader (cf https://www.objectaid.com/pricing).
Pour l'installer sur eclipse, il faut : 
1) Copier : http://www.objectaid.com/update/current/site.xml
2) Sur Eclipse : Help> Install New Software : sur work with : coller le lien ci-dessus.
3) Cocher ObjectAid Diagram Add-On puis cliquer sur Next
4) Accepter la licence puis installer le logiciel
5) Redémarrer eclipse.
Je vais également vous le mettre en .png dans le Doc et ce fichier .ucls dans le Doc également.

2019-06-07 19:22 UTC, oliviercailloux commented
> Je pense que l'on peut l'utiliser de manière gratuite à condition de ne pas l'upgrader (cf https://www.objectaid.com/pricing).
Je ne pense pas, c’est seulement une « evaluation version ».

2019-06-07 19:25 UTC, oliviercailloux requested changes
Je ne vois pas le png.

2019-06-12 09:20 UTC, jacquesmoati commented
@oliviercailloux @aliliKM (prochaine SMPO)
J'ai tout mis dans le fichier Doc avec le png comme demandé et j'ai gardé le .ucls pour nous sur eclispe.
@aliliKM Comme Monsieur Cailloux l'a expliqué il ne faut plus utiliser Object Aid UML car elle est sous "evaluation version", il faut donc utiliser IMB Rationel par exemple pour la delivery 3.

2019-06-13 16:13 UTC, oliviercailloux commented
Voudriez-vous me fournir un PNG plus agréable à lire que cet alignement horizontal de classes, au format 4/3 par exemple ?

2019-06-25 10:02 UTC, jacquesmoati commented
@oliviercailloux 
Je ne sais pas comment on convertit dans ce format de png. J'ai pourtant cherché sur le web.
Pourriez-vous m'indiquer comment ? Merci

2019-06-26 01:14 UTC, oliviercailloux commented
Je ne comprends pas votre question. Vous m’avez déjà fourni un PNG ! Vous devez savoir comment faire, j’imagine, pour produire un PNG.

Pour agencer les classes, utiliser un éditeur d’image, au pire, mais de préférence, modifier le source de manière à ce qu’il génère un PNG plus joli.

De toute façon, il est maintenant un peu tard pour se concentrer là-dessus, j’imagine.

2019-06-26 08:26 UTC, nikolaspaci commented
PR plus d'actualité ==> fermeture de la PR

2019-06-26 08:26 UTC, closed without merging