update readme delivery 3
13tomoore/J-Confs pull request #17
Opened 2019-06-10 21:20 UTC by aliliKM

Mis à jour du ReadMe - Livraison 3

2019-06-11 12:18 UTC, oliviercailloux requested changes

2019-06-11 12:18 UTC, oliviercailloux commented on README.adoc
> +|3|17th May,2019 | 15 h| link:https://github.com/aliliKM[Alison Koudossou Messan]| Team 1 : Nikola & Tom +
espace après virgule
10h, pas 15h (deux séances).

2019-06-11 12:18 UTC, oliviercailloux commented on README.adoc
>  	    . Write an email @ __Jean-Christophe Gay__ asking him clear explanation of how to access to the intranet of the Université Paris-Dauphine +
Ces tâches sont-elles réellement toutes accomplies ? J’en doute. Par exemple, je doute que le document sur l’accès à l’intranet soit rédigé.

De toute façon, je ne requiert pas que vous gardiez une trace précise de ce que vous avez fait (mais ça peut vous être utile pour la présentation finale). Vous devez par contre continuer à suivre les tâches pas encore finies, à moins de décider de les abandonner, mais c’est dans ce cas à discuter avec moi.

2019-06-12 16:54 UTC, aliliKM commented
Modifications faites en fonction des commentaires.

2019-06-13 16:30 UTC, oliviercailloux approved these changes

2019-06-13 18:30 UTC, merged