Add constructor
13tomoore/J-Confs pull request #19
Opened 2019-06-13 21:06 UTC by aliliKM

Ajout des constructeurs Researcher et Conference. Livraison 3.

2019-06-16 22:41 UTC, oliviercailloux requested changes
FORMAT

2019-06-16 22:41 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/jconfs/Conference.java
> +	}
Protection contre null et autres valeurs de paramètres incorrectes. BP null, …
Si certains champs sont facultatifs, prévoyez un autre constructeur plus minimaliste pour que ce soit clair.
Je pense qu’une conférence doit avoir au moins une date de début et de fin, le reste me semble a priori facultatif.

2019-06-16 22:41 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/jconfs/Conference.java
> +
Indiquez que la classe est immuable, si telle est votre intention.

2019-06-16 22:41 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/jconfs/ConferenceReader.java
> +			e.printStackTrace();
EXC

2019-06-16 22:41 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/jconfs/ReadCalendarFiles.java
> +	public static Conference createConference(String filepath) throws IOException, ParserException {
ReadCalendarFiles et ConferenceReader ne font-ils pas la même chose ? Je ne vois pas la différence. En tous cas, il y a un problème de duplication de code à résoudre.

2019-06-16 22:41 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/jconfs/Researcher.java
> +	 * @param surname not <code>null</code>.
Ce n’est plus `surname`

2019-06-16 22:41 UTC, oliviercailloux commented on src/test/java/TestConferenceWriter.java
>  	public static void main (String [] args) throws Exception {
Ce « test » ne teste rien. Effacez-le simplement.

2019-06-20 08:33 UTC, aliliKM commented
Modifications effectuées

2019-06-20 14:31 UTC, oliviercailloux requested changes
FOCUS (sept fichiers changés ?)

2019-06-20 14:31 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/jconfs/Conference.java
> + * @author Alison This class is immutable.
Veuillez observer le résultat de votre commentaire et ajuster. Ne pas effacer les auteurs précédents.

2019-06-20 14:31 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/jconfs/Conference.java
> +	}
Pourquoi avoir marqué ceci comme Resolved ? Une partie du problème (première ligne du commentaire) est toujours présent.

2019-06-20 14:31 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/jconfs/Conference.java
> +	public Conference(String startDate, String endDate) {
Tant qu’on y est, accepter des paramètres de types corrects, à savoir des `LocalDate`.

2019-06-20 14:31 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/jconfs/Conference.java
>  	public Conference(URL url) {
La présence de ce constructeur est incompatible avec mon commentaire précédent. Est-il nécessaire ?

2019-06-22 08:01 UTC, oliviercailloux requested changes
FOCUS : huit fichiers changés, sont-ils vraiment tous liés à votre tâche ?

2019-06-22 18:19 UTC, aliliKM commented
Les classes ConferenceReader, GuiConference, ReadCalendarFiles, Researcher, ResearcherBuilder, TestConferenceWriter et TestCalendarOnline ont été impacté par la suppression des setters et du constructeur Conference(URL url) de la classe Conference. Je me suis donc chargé de régler les problèmes causés par la modification de cette classe.

2019-06-26 10:52 UTC, oliviercailloux requested changes
FORMAT

2019-06-26 10:52 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/jconfs/conference/Conference.java
> +	public Conference(URL url, String title, String startDate, String endDate, Double registrationFee, String country,
Si vous forcez `uid` ≠ `null`, vous ne pouvez pas également prévoir un constructeur sans cette information ! Il faut choisir.

Par ailleurs, ce n’est pas la responsabilité de cette classe de convertir des dates, cela n’a rien à voir et devrait être fait à l’extérieur de cette classe (dans le GUI ou plus généralement lors de la lecture des données depuis le monde extérieur).

2019-06-26 10:52 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/jconfs/conference/Conference.java
> +	public Conference(String uid,LocalDate startDate, LocalDate endDate) {
Factorisez (BP local design). Tous les constructeurs doivent appeler votre constructeur le plus général, celui qui accepte tous les champs, pour point central de vérification de paramètres.

2019-06-26 10:52 UTC, oliviercailloux commented on src/test/java/TestConferenceWriter.java
>  	public static void main (String [] args) throws Exception {
Pourquoi conserver cette classe vide ?

2019-06-26 17:14 UTC, aliliKM commented
Les modifications demandées ont été effectuées.
Le paramètre "uid" n'est pas encore présent dans toutes les classes mais à l'avenir, nous souhaitons qu'il soit not null.

2019-06-27 08:00 UTC, oliviercailloux approved these changes
Approbation malgré problème FORMAT toujours présent

2019-06-27 18:47 UTC, nikolaspaci commented
Problème formatage résolu , merge dans master.

2019-06-27 18:47 UTC, merged