Warnings
13tomoore/J-Confs pull request #21
Opened 2019-06-17 14:53 UTC by feLlx

Après ajout du fichier "import.epf", nous avons constaté de nombreux warnings. 
Cette branche a eu pour but de les résoudre. 
Les seuls warnings restants sont ceux de la classe "Main" et de la classe "GeneralGUITest" qui seront supprimés dans la branche "DeleteUnusedClass"

2019-06-17 15:59 UTC, oliviercailloux requested changes
Résoudre les problèmes au lieu d’utiliser @SuppressWarnings (ils peuvent être justifiés occasionnellement mais il faut savoir pourquoi dans ce cas).

2019-06-17 15:59 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/geocode/ReverseGeoCode.java
> +        @SuppressWarnings("resource")
Résoudre le problème au lieu de le masquer.

2019-06-17 15:59 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/jconfs/ConferenceReader.java
> +		@SuppressWarnings("unused")
Résoudre le problème

2019-06-20 18:56 UTC, feLlx commented on src/main/java/io/github/oliviercailloux/y2018/geocode/ReverseGeoCode.java
> +        @SuppressWarnings("resource")
Problème résolue : utilisation d'un try-with-ressouces

2019-06-20 18:57 UTC, feLlx commented on src/main/java/io/github/oliviercailloux/y2018/jconfs/ConferenceReader.java
> +		@SuppressWarnings("unused")
Problème résolue : suppression du type redondant pour le LinkedHashSet

2019-06-21 09:03 UTC, oliviercailloux requested changes
INSTR (conflits)

2019-06-22 12:26 UTC, feLlx commented
Conflits résolus

2019-06-22 15:14 UTC, oliviercailloux requested changes

2019-06-22 15:14 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/jconfs/ConferenceWriter.java
>  	private static Calendar createCalendar() {
Effacer plutôt cette méthode inutile.

2019-06-22 15:14 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/jconfs/ConferencesFromICal.java
> +	@SuppressWarnings("resource")
Résoudre le problème au lieu de le masquer.

2019-06-22 15:14 UTC, oliviercailloux commented on src/test/java/io/github/oliviercailloux/y2018/TestConferenceReader.java
> +	@SuppressWarnings("unused")
Résoudre le problème au lieu de le masquer.

2019-06-22 15:26 UTC, feLlx commented on src/main/java/io/github/oliviercailloux/y2018/jconfs/ConferenceWriter.java
>  	private static Calendar createCalendar() {
Méthode effacer

2019-06-22 15:27 UTC, feLlx commented on src/main/java/io/github/oliviercailloux/y2018/jconfs/ConferencesFromICal.java
> +	@SuppressWarnings("resource")
Problème résolue : utilisation d'un try-with-ressouces

2019-06-22 15:28 UTC, feLlx commented on src/test/java/io/github/oliviercailloux/y2018/TestConferenceReader.java
> +	@SuppressWarnings("unused")
Annotation supprimée

2019-06-22 17:21 UTC, oliviercailloux approved these changes
Il aurait été mieux que le code soit formaté proprement, mais ok pour fusion à ce stade.

2019-06-22 18:16 UTC, merged