Livraison 3 - Auto size gui conf
13tomoore/J-Confs pull request #23
Opened 2019-06-20 08:29 UTC by aliliKM

Application des bonnes pratiques concernant l'automatisation des boutons et des champs.

2019-06-20 13:52 UTC, oliviercailloux requested changes
FORMAT
Raccourcir les méthodes longues, par exemple en découpant en plusieurs méthodes.

2019-06-20 13:52 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/jconfs/GuiConference.java
>  					e.printStackTrace();
Envoyer plutôt une exception runtime appropriée en fonction de la situation.

2019-06-20 13:52 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/jconfs/GuiConference.java
>  		btn_researcher.addSelectionListener(new SelectionAdapter() {
ECL

Ce code imbriqué dans des blocs imbriqués est difficilement lisible. Utiliser une référence de méthode comme vu au cours.

2019-06-20 13:52 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/jconfs/GuiConference.java
> +		// To dev at the second iteration
BP Style comments

2019-06-20 13:52 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/jconfs/GuiConference.java
> +	}
Avez-vous testé votre code ? Ceci ne sert à rien.

2019-06-20 13:52 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/jconfs/GuiConference.java
> +	public static boolean check(String start, String end, DateTime dateStart, DateTime dateEnd, Conference conf,
Une seule méthode `check` pour tout ne simplifie pas les choses. Séparer en plusieurs méthodes, chacune pour une vérification plus simple.

2019-06-20 13:52 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/jconfs/GuiConference.java
> +		String[] array = {"1","2", "3", "4", "5", "6", "7", "8", "9"};
Utiliser une collection et non un array, mais ici, on n’a même pas besoin d’une telle liste.

2019-06-21 07:47 UTC, feLlx commented on src/main/java/io/github/oliviercailloux/y2018/jconfs/GuiConference.java
> +	}
Oui. Mais en effet, ce code ne sert à rien, il a été réalisé par le groupe précédent. En attendant que la PR 19 (avec un constructeur propre) soit validé, je dois laisser ce code sinon, le build Travis ne compilera pas.

2019-06-22 14:09 UTC, feLlx commented on src/main/java/io/github/oliviercailloux/y2018/jconfs/GuiConference.java
> +		String[] array = {"1","2", "3", "4", "5", "6", "7", "8", "9"};
En effet, cet array mis au point par l'ancien groupe ne sert à rien. Suppression de cette array.

2019-06-22 14:13 UTC, feLlx commented on src/main/java/io/github/oliviercailloux/y2018/jconfs/GuiConference.java
> +	public static boolean check(String start, String end, DateTime dateStart, DateTime dateEnd, Conference conf,
Division en deux méthodes :
- une méthode qui renvoie un boolean selon si la date de début est antérieur ou non à la date de fin.
- une méthode qui renvoie un string. Ce string correspond à une date au format dd/mm/yyyy (cette seconde méthode sera à revoir une fois la PR 19 accepté... étant donné que le type de la date d'une conférence passe d'un String à un LocalDate).

2019-06-22 16:27 UTC, feLlx commented on src/main/java/io/github/oliviercailloux/y2018/jconfs/GuiConference.java
> +		// To dev at the second iteration
Commentaire supprimée.

2019-06-22 16:29 UTC, feLlx commented on src/main/java/io/github/oliviercailloux/y2018/jconfs/GuiConference.java
>  		btn_researcher.addSelectionListener(new SelectionAdapter() {
warnings résolues
code divisé avec des références de méthodes. Ces méthodes pourront d'ailleurs être encore réduites une fois la PR 19 validée (cela supprimera les setters inutiles).

2019-06-22 16:31 UTC, feLlx commented on src/main/java/io/github/oliviercailloux/y2018/jconfs/GuiConference.java
> +	}
En attendant de pouvoir supprimer les setters, ces variables inutiles crées par l'ancien groupe ont été supprimées. Les setters ont quant à eux été déplacés hors de la fonction.

2019-06-23 12:26 UTC, feLlx commented on src/main/java/io/github/oliviercailloux/y2018/jconfs/GuiConference.java
>  					e.printStackTrace();
Correction, throw new runtimeexception

2019-06-24 09:30 UTC, oliviercailloux requested changes
FORMAT, EXC

Vos méthodes doivent toutes être des méthodes d’instance, pas des méthodes statiques (pour application future simplifiée des principes orienté-objet telle que découpe en sous-objets).

2019-06-24 09:30 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/jconfs/GuiConference.java
> +	}
REUSE. Remplacer par un code de deux ou trois lignes garanti correct en utilisant l’API appropriée (voir par exemple https://docs.oracle.com/javase/tutorial/datetime/).

2019-06-24 09:30 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/jconfs/GuiConference.java
> +			throw new RuntimeException(e1);
Soyez plus explicites SVP. Ici par exemple, `AssertionError` semble appropriée, car on peut raisonnablement supposer que le problème ne se produira pas par déduction logique.

2019-06-24 09:30 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/jconfs/GuiConference.java
> +			e1.printStackTrace();
EXC

2019-06-24 09:30 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/jconfs/GuiConference.java
> +				throw new RuntimeException(e1);
Choix imparfait mais ok pour le moment car difficile ici de faire beaucoup mieux facilement.

2019-06-24 09:30 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/jconfs/GuiConference.java
> +		if (dateCheck(start, end) == true){
Ne pas comparer un booléen à true, ça ne sert à rien !

Le problème vient du fait que votre méthode `dateCheck` est mal nommée, cela donne envie d’écrire ce genre de code. Appelez-la d’un nom décrivant ce qu’elle renvoie, par exemple `isDateValid`.

2019-06-24 09:30 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/jconfs/GuiConference.java
> +		}
Factorisez ! Ce code est presque identique au code de `generateCalendar`. Réutilisez le code au lieu de le dupliquer.

2019-06-25 16:55 UTC, feLlx commented on src/main/java/io/github/oliviercailloux/y2018/jconfs/GuiConference.java
> +		if (dateCheck(start, end) == true){
Nom de méthode changé

2019-06-25 16:56 UTC, feLlx commented on src/main/java/io/github/oliviercailloux/y2018/jconfs/GuiConference.java
> +			e1.printStackTrace();
Modification : throw new IllegalArgumentException

2019-06-25 16:56 UTC, feLlx commented on src/main/java/io/github/oliviercailloux/y2018/jconfs/GuiConference.java
> +			throw new RuntimeException(e1);
Modification apportée

2019-06-25 17:40 UTC, feLlx commented on src/main/java/io/github/oliviercailloux/y2018/jconfs/GuiConference.java
> +	}
Utilisation de LocalDate

2019-06-25 18:37 UTC, feLlx commented on src/main/java/io/github/oliviercailloux/y2018/jconfs/GuiConference.java
> +		}
Factorisation effectuée

2019-06-26 08:21 UTC, oliviercailloux approved these changes

2019-06-26 08:21 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/jconfs/conference/Conference.java
> +		this.endDate = endDate;
Protection contre `null` ?

2019-06-26 16:55 UTC, feLlx commented on src/main/java/io/github/oliviercailloux/jconfs/conference/Conference.java
> +		this.endDate = endDate;
Objects.requirenonnull ajouté

2019-06-26 18:55 UTC, merged