Tasks : Update dependencies
13tomoore/J-Confs pull request #4
Opened 2019-05-19 10:51 UTC by feLlx

Tasks : 1) Update dependencies if possible (Junit, Guava, as well as dependencies of different environments)

2019-05-20 16:59 UTC, oliviercailloux requested changes

2019-05-20 16:59 UTC, oliviercailloux commented on pom.xml
> +			<version>4.13-beta-3</version>
Évitez les versions bêta, c’est un risque. Prenez la plus récente qui n’est pas bêta (ni alpha).

2019-05-20 16:59 UTC, oliviercailloux commented on pom.xml
>  					<version>4.3</version>
Version incorrecte datée de 2015. Voir document SWT dans cours SVP.

2019-05-20 18:54 UTC, feLlx commented
Changement de version Junit : 4.12
Changement de version SWT pour tous les os comme indiqué dans le cours
Ajout de JFace comme indiqué dans le cours

2019-05-23 06:13 UTC, oliviercailloux commented
Résoudre pbl Travis SVP

2019-05-23 07:34 UTC, feLlx commented
Problème Travis réglé pour cette branche et ce pr
Nous avons besoin que ce pr soit validé, pour que le problème Travis des autres branches soit résolu

2019-05-23 07:52 UTC, oliviercailloux approved these changes
Ok mais il faut ajouter de la javadoc pour expliquer pourquoi vous avez désactivé les tests en question.

2019-05-23 07:54 UTC, merged