Guava
13tomoore/J-Confs pull request #5
Opened 2019-05-19 16:38 UTC by feLlx

@oliviercailloux 
En modifiant et appliquant guava je me suis rendu compte que les bonnes pratiques pour éviter d'avoir des nulls n'étaient pas appliquées pour les constructeurs. En effet le groupe précédent a implémenté des constructeurs avec un seul paramètre puis rempli les attributs de l'instanciation avec des sets juste après son appel. Cela induit une erreur lorsque l'on lit la classe, on peut penser qu'il est possible de mettre certains attributs à null alors que non. Cela pourrait donc être une prochaine tâche pour une prochaine livraison : fouiller le code et trouver les différents appels de constructeurs et le remplacer par un constructeur mieux construit qui respecte les bonnes pratiques.

2019-05-20 17:40 UTC, oliviercailloux requested changes
FORMAT

2019-05-20 17:40 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/jconfs/Conference.java
> +		this.title = Preconditions.checkNotNull(title,"Your conference must have a title");
Privilégier Objects.requireNonNull, qui fait la même chose mais est standard.
L’ajout d’un string ne nuit pas, mais n’est pas non plus très utile, je pense que votre temps serait mieux utilisé à d’autres choses. Ces informations servent aux développeurs, pas à l’utilisateur final. Le développeur verra facilement quel est le problème sans avoir besoin du message, grâce à l’exception.

2019-05-20 17:41 UTC, oliviercailloux commented
Attention, pour toutes vos tâches à venir, il faut en priorité résoudre le problème du build Travis.

2019-05-20 17:42 UTC, oliviercailloux commented
Veuillez ouvrir les Issues de votre projet SVP, cela peut m’être utile.

2019-05-23 07:35 UTC, feLlx commented on src/main/java/io/github/oliviercailloux/y2018/jconfs/Conference.java
> +		this.title = Preconditions.checkNotNull(title,"Your conference must have a title");
Correction demandée effectuée

2019-05-23 09:24 UTC, oliviercailloux requested changes
Toujours FORMAT, et toujours Issues à ouvrir.
INSTR FOLLOW-UP

2019-05-24 13:34 UTC, aliliKM commented
Onglet issue(s) ouverte(s) - FORMAT problème résolue
PR Itération 2

2019-05-26 10:13 UTC, oliviercailloux approved these changes
ok moyennant qqs broutilles, corrigez puis fusionnez.

2019-05-26 10:13 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/jconfs/Conference.java
>  	public void setFeeRegistration(Double registrationFee) {
Si vous vouliez rendre ce paramètre obligatoire, il devrait être de type primitif `double`, pas `Double` (et retirer `not null` qui deviendrait inutile).

2019-05-26 10:13 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/jconfs/Conference.java
>  	 * This is a setter which set the country
Tant que vous y êtes, retirez ce genre de commentaire inutile. Ou indiquez de façon plus courte : `Sets the country.`

2019-05-26 10:13 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/jconfs/Researcher.java
> +	 * @param surname
Légère préférence personnelle pour `lastname` (opposition claire avec `firstname`, américain et utilisé aussi au RU)

2019-05-27 16:49 UTC, aliliKM commented
Dernières modifications effectuées - Itération 2

2019-05-27 16:57 UTC, merged